version: '2'

services:
  app:
    image: 'oven:latest'
    build:
      context: .
    container_name: oven_svc
    depends_on:
      - oven_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://oven_db:5432/oven_svc
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=borojolo
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
    expose:
      - "8080"
          
  oven_db:
    image: 'postgres:15.2-alpine'
    container_name: oven_db
    environment:
      - POSTGRES_DB=oven_svc
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=borojolo
      - PFDATA=/data/oven_db
    ports:
      - "5432:5432"
    volumes:
       - ./data:/var/lib/postgresql/data
volumes:
  app:
    driver: local